### ISSUE TITLE
Not working with Click 8?

### ISSUE THREAD

**Issue by wabiloo** [jwodder/click-loglevel#1]
When I try to use this in my code, I get a TypeError 
`isinstance() arg 2 must be a type, a tuple of types, or a union`

Here is my code:

```
@click.option(
    "-l",
    "--log-level", 
    type=LogLevel(),
    required=False,
    help="Log level"
)
@click.pass_context
def cli(ctx, tenant, log_level):
    if log_level:
        set_console_logging_level(log_level)
```

I'm wondering if it's linked to the fact I'm using Click 8...?

**Comment by jwodder** [comment]
If I convert your code into a runnable script as follows:

```python
import click
from click_loglevel import LogLevel

@click.command()
@click.option(
    "-l",
    "--log-level",
    type=LogLevel(),
    required=False,
    help="Log level"
)
def cli(log_level):
    print(repr(log_level))

if __name__ == "__main__":
    cli()
```

and run it with Click 8.1.3 and click-loglevel 0.4.0.post1, it works fine.  Can you provide a complete runnable script that exhibits the behavior you're seeing?

**Comment by wabiloo** [comment]
My bad, sorry.
The issue was in another part of the code, also exposed by a new test that was triggering click-loglevel so I (wrongly) concluded it was linked to your package.

The click exceptions are sometimes difficult to identify and trace...

Thanks for checking on your end!
